server:
  tomcat:
    uri-encoding: UTF-8
  port: 8000

spring:
  datasource:
    username: root
    password: 2000106
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://********:3306/spark_web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dev.dataviewspring.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
